; ===============================================================
; Curve / Table Forge demo - 16-bit sprite X (Ease Out Bounce)
; A ball bounces horizontally across the full screen width using a
; lo/hi split table generated by Table Forge (0..320, sprite 0).
; The index loops 0..113 once per frame (~50 values/sec = tempo 50
; in the Table Forge preview), so it moves exactly like the preview.
; ===============================================================

* = $0801

start:
    sei

    lda #$00
    sta $d020            ; border black
    sta $d021            ; background black

    .sprite_init 0, 7, $80   ; sprite 0, yellow, data page $80 ($2000)
    .sprite_pos 0, 24, 120   ; initial pos; X is overwritten each frame

    lda #$00
    sta idx

main:
    .wait_raster $f8

    ldx idx
    jsr table_set_x      ; sprite 0 X = table[idx] (handles $D010 MSB)

    inc idx
    lda idx
    cmp #$72             ; 114 entries -> wrap back to 0
    bcc main
    lda #$00
    sta idx
    jmp main

idx:
    .byte $00

; -----------------------------------------------
; Table Forge - Ease Out Bounce  (16-bit, sprite 0)
; Range: 0..320   Count: 114 entries (228 bytes)
; Two parallel tables, index BOTH with the same X:
;   table_lo[X] = low 8 bits   -> $D000
;   table_hi[X] = 9th bit (0/1) -> $D010 bit 0
; -----------------------------------------------
table_lo:
    .byte $00, $00, $01, $02, $03, $05, $07, $09
    .byte $0C, $0F, $13, $17, $1B, $1F, $24, $2A
    .byte $30, $36, $3C, $43, $4A, $52, $5A, $63
    .byte $6B, $74, $7E, $88, $92, $9D, $A8, $B3
    .byte $BF, $CB, $D7, $E4, $F1, $FF, $0D, $1B
    .byte $2A, $39, $3C, $35, $2E, $27, $21, $1B
    .byte $15, $10, $0C, $07, $03, $00, $FC, $FA
    .byte $F7, $F5, $F3, $F2, $F1, $F0, $F0, $F0
    .byte $F1, $F1, $F3, $F4, $F6, $F9, $FB, $FE
    .byte $02, $06, $0A, $0F, $14, $19, $1F, $25
    .byte $2B, $32, $39, $40, $3C, $39, $36, $33
    .byte $31, $2F, $2E, $2D, $2C, $2C, $2C, $2D
    .byte $2D, $2F, $30, $32, $34, $37, $3A, $3E
    .byte $3F, $3E, $3C, $3C, $3B, $3B, $3B, $3C
    .byte $3D, $3E
table_hi:
    .byte $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $01, $01
    .byte $01, $01, $01, $01, $01, $01, $01, $01
    .byte $01, $01, $01, $01, $01, $01, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00
    .byte $01, $01, $01, $01, $01, $01, $01, $01
    .byte $01, $01, $01, $01, $01, $01, $01, $01
    .byte $01, $01, $01, $01, $01, $01, $01, $01
    .byte $01, $01, $01, $01, $01, $01, $01, $01
    .byte $01, $01, $01, $01, $01, $01, $01, $01
    .byte $01, $01

; --- Set sprite 0 X from the 16-bit table (index in X) ---
; Usage:  ldx #index  /  jsr table_set_x
table_set_x:
    lda table_lo,x
    sta $d000            ; sprite 0 X low byte
    lda table_hi,x
    beq table_clr_msb
    lda $d010
    ora #%00000001       ; set sprite 0 MSB
    sta $d010
    rts
table_clr_msb:
    lda $d010
    and #%11111110       ; clear sprite 0 MSB
    sta $d010
    rts

* = $2000

.include "ball.asm"
